### PR TITLE
Update computeStateDisplay to support new translation_key

### LINKED ISSUE #292: As of 2023.4.3 the m-e-row shows status of people as raw home/not_home instead of Home/Away
After upgrade to 2023.4.3 from 2023.4.2, the status of people is being shown as home/not_home (the real state string) and not the friendly version. 

image

### PR DESCRIPTION
**Pull request by mill1000**
Close #292, #290, and maybe #289

### CODE REVIEW

**Comment by jeremywillans** [comment]
@benct, can you please review this PR ?

**Comment by kukulich** [comment]
@mill1000 Is it possible to support translated attribute values as well?

**Comment by mill1000** [comment]
Yes it's possible but likely best for a separate PR. It would need to implement something like [computeAttributeValueDisplay](https://github.com/home-assistant/frontend/blob/15eab18e07589d7c0efc3eef92c103047f880a4a/src/common/entity/compute_attribute_display.ts#LL19C14-L19C43)

**Comment by iankaufmann** [comment]
While waiting for an official update, I have tried to replace my local "multiple-entity-row.js" file with the one from this pull request.

I've chosen "Reload Resources" from the menu, and cleared cache.

Doesn't seem to change how things are displayed.  Still says "off" and "on" instead of "Closed" and "Open".

Is there something I'm missing to make this work?

**Comment by mill1000** [comment]
What if you gzip `multiple-entity-row.js`? e.g. `gzip multiple-entity-row.js`

**Comment by iankaufmann** [comment]
> What if you gzip `multiple-entity-row.js`? e.g. `gzip multiple-entity-row.js`

Interesting, I was wondering what was up with the .gz file.  That worked!  Makes sense now.

Thank you!

**Comment by GRClark** [comment]
Any update on this?  I’m unfamiliar with how long the role was takes for pull requests to become published updates but eager to have this fixed so that I can once again upgrade HA.

**Comment by wigster** [comment]
Unfortunately it seems there is no activity from @benct on GitHub since Dec 22.

**Comment by kukulich** [comment]
https://github.com/benct/lovelace-multiple-entity-row/issues/291#issuecomment-1512723546

**Comment by GRClark** [comment]
Does anyone know how to take these files and use them?  I saw the gzip comment and confused by it.  Not familiar with how to do that.  Using Home Assistant IN Docker environment.

**Comment by jeremywillans** [comment]
@GRClark, replace/overwrite the .js file and delete the gzip from the directory - once you refresh your browser/cache, the updated values should show. for the mobile app, open the settings and select the reload frontend cache option.

**Comment by mill1000** [comment]
@benct Thanks Ben!

**Comment by benct** [comment]
Released in version 4.5.0. I'm not myself on HA 2023.4 or later yet, so please let me know if it works as expected.

**Comment by d3relict** [comment]
updated, works as expected on Home Assistant 2023.5.3, Frontend 20230503.3 - latest
thanks to all of you!

**Pull request merged**
