### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by techillin**
Locale-aware number formatting

### CODE REVIEW

**Comment by benct** [comment]
Thanks!

**Comment by bcutter** [comment]
Now some attributes look strange. E. g. this is shown with , instead of . --> how to configure this?

image

image

**Comment by benct** [comment]
Numbers are now formatted according to your locale, which apparently use commas and not period. You'll have to change locale/language in HA settings to change this.

**Comment by bcutter** [comment]
Have a look at the first screenshot. It's from more info card. It uses dots correctly. Multiple-entity-row is misinterpreting something here.

Give us control on a per entity/attribute basis to set the view individually.

**Comment by benct** [comment]
Was using the wrong field from HA to handle locale. Should be fixed in version `4.3.1`.

**Comment by bcutter** [comment]
> Was using the wrong field from HA to handle locale. Should be fixed in version `4.3.1`.

Thanks for looking into this so quickly. I updated to 4.3.1, additionally reset Frontensegeln cache and I'm sorry to report it still shows those two attributes wrong while in raw (dev tools) it's shown correctly:

image

**Comment by bcutter** [comment]
OK I found more and more places this crashed my views. It's completely bogus why version information of entities or attributes is shown with commata instead of points now (version "5,6", that's really strange). Versioning is not a matter of location awareness. Guess I need to file an issue bout this, right.

**Comment by bcutter** [comment]
@benct please have a look at https://community.home-assistant.io/t/multiple-entity-row-card-local-number-formatting-update-broke-view/370718 for examples when this local number awareness feature is going too far.

It's behavior is completely random.

**Pull request merged**
