### PR TITLE
fix tap-action url

### PR DESCRIPTION
**Pull request by Knapoc**
fixes: #54

### CODE REVIEW

**Comment by benct** [comment]
I wanted to properly support the `focus` call without the optional chaining operator I mistakenly added, so I had to make a few more changes than just removing the question mark (be8b9c190cd284238c20ebe14d2b5fed304fc2e2). Still, thanks for contributing and helping :)

**Comment by Knapoc** [comment]
out of curiosity since I'm not a programmer - just able to read code: is there a difference between chaining the functions and your implementation? I don't understand the need for the third `if`-statement.

**Comment by benct** [comment]
The function `window.open()` returns a window wrapper object if it is able to open a new window. In some cases however this can fail, resulting in returning `null`. If that happens, the chaining will be `null.focus()` which will cause an error and break the card. The last if statement checks that the window object is not `null` before calling `focus()` on it.

**Comment by Knapoc** [comment]
Thank you!

**Pull request closed without merging**
